docker_image_debian:
  image: docker:20
  stage: build
  services:
    - docker:20-dind
  script:
    - cd ci/
    - docker build -t $CI_REGISTRY/striezel/webp-viewer/debian:11 . -f Dockerfile_debian
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/striezel/webp-viewer/debian:11
    - docker logout $CI_REGISTRY
  # Only build new image when the Dockerfile or the GitLab CI configuration
  # changes.
  only:
    changes:
      - ci/Dockerfile_debian
      - .gitlab-ci.yml

debian:
  image: registry.gitlab.com/striezel/webp-viewer/debian:11
  stage: test
  before_script:
    - apt-get update && apt-get -y upgrade
  script:
    # build
    - export CXX=g++-10
    - export CC=gcc-10
    - mkdir build
    - cd build
    - cmake ../
    - make -j4
    # tests
    - ctest -V

docker_image_fedora:
  image: docker:20
  stage: build
  services:
    - docker:20-dind
  script:
    - cd ci/
    - docker build -t $CI_REGISTRY/striezel/webp-viewer/fedora:35 . -f Dockerfile_fedora
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/striezel/webp-viewer/fedora:35
    - docker logout $CI_REGISTRY
  # Only build new image when the Dockerfile or the GitLab CI configuration
  # changes.
  only:
    changes:
      - ci/Dockerfile_fedora
      - .gitlab-ci.yml

fedora:
  image: registry.gitlab.com/striezel/webp-viewer/fedora:35
  stage: test
  before_script:
    - yum update -y
  script:
    # build
    - export CXX=g++
    - export CC=gcc
    - mkdir build
    - cd build
    - cmake ../
    - make -j4
    # tests
    - ctest -V

package_debian:
  image: debian:11-slim
  stage: build
  before_script:
    - ./ci/01-install-dependencies.sh
  script:
    - ./ci/02-create-package.sh
  only:
    - tags
  artifacts:
    paths:
      - "webp-viewer*.deb"
