debian:
  image: debian:11-slim
  stage: test
  before_script:
    - apt-get update && apt-get -y upgrade
    - apt-get install -y catch cmake g++-10 libgl-dev libglfw3-dev libwebp-dev pkg-config
  script:
    # build
    - export CXX=g++-10
    - export CC=gcc-10
    - mkdir build
    - cd build
    - cmake ../
    - make -j4
    # tests
    - ctest -V

fedora:
  image: fedora:35
  stage: test
  before_script:
    - yum update -y
    - yum install -y catch-devel cmake gcc-c++ glfw-devel libwebp-devel pkgconfig
  script:
    # build
    - export CXX=g++
    - export CC=gcc
    - mkdir build
    - cd build
    - cmake ../
    - make -j4
    # tests
    - ctest -V

package_debian:
  image: debian:11-slim
  stage: build
  before_script:
    - ./ci/01-install-dependencies.sh
  script:
    - ./ci/02-create-package.sh
  only:
    - tags
  artifacts:
    paths:
      - "webp-viewer*.deb"
