# This Dockerfile builds the image used during the debian build job on GitLab.
FROM debian:13-slim
LABEL maintainer="Dirk Stolle <striezel-dev@web.de>"
# Always update any existing packages first.
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get upgrade -y
# Install build toolchain and dependencies.
RUN apt-get install -y catch2 cmake g++-14 libgl-dev libglfw3-dev libwebp-dev pkg-config
ENV CXX=g++-14
ENV CC=gcc-14
RUN export CXX=g++-14
RUN export CC=gcc-14
