name: GCC

on: push

jobs:
  gcc:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        version: [9, 10, 11, 12]
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch2 cmake g++-${{ matrix.version }} libglfw3-dev libgl-dev libwebp-dev pkg-config
      - name: Build with GNU GCC ${{ matrix.version }}
        run: |
          export CXX=g++-${{ matrix.version }}
          export CC=gcc-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../
          make -j2
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
      - name: Build with GNU GCC ${{ matrix.version }}, statically linking standard libraries
        run: |
          export CXX=g++-${{ matrix.version }}
          export CC=gcc-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build_static_std_libs
          cd build_static_std_libs
          cmake ../ -DENABLE_LTO=ON -DENABLE_STATIC_STANDARD_LIBRARIES=ON
          make -j2
        if: matrix.version == 12
      - name: Tests of build with statically linked standard libraries
        run: |
          cd "$GITHUB_WORKSPACE"/build_static_std_libs
          ctest -V
        if: matrix.version == 12
