name: Build Debian packages

on:
  push:
    tags:
      - v*

jobs:
  package:
    strategy:
      fail-fast: false
      matrix:
        include:
        - image: 'debian:11'
          pack-name: 'debian_11_amd64'
          runner: ubuntu-24.04
        - image: 'debian:11'
          pack-name: 'debian_11_arm64'
          runner: ubuntu-24.04-arm
        - image: 'debian:12'
          pack-name: 'debian_12_amd64'
          runner: ubuntu-24.04
        - image: 'debian:12'
          pack-name: 'debian_12_arm64'
          runner: ubuntu-24.04-arm
        - image: 'ubuntu:20.04'
          pack-name: 'ubuntu_20_04_amd64'
          runner: ubuntu-24.04
        - image: 'ubuntu:20.04'
          pack-name: 'ubuntu_20_04_arm64'
          runner: ubuntu-24.04-arm
        - image: 'ubuntu:22.04'
          pack-name: 'ubuntu_22_04_amd64'
          runner: ubuntu-24.04
        - image: 'ubuntu:22.04'
          pack-name: 'ubuntu_22_04_arm64'
          runner: ubuntu-24.04-arm
        - image: 'ubuntu:24.04'
          pack-name: 'ubuntu_24_04_amd64'
          runner: ubuntu-24.04
        - image: 'ubuntu:24.04'
          pack-name: 'ubuntu_24_04_arm64'
          runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    container: ${{ matrix.image }}
    steps:
      - name: Install Debian packages
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update && apt-get upgrade -y
          apt-get install -y --no-install-recommends build-essential bzip2 ca-certificates debhelper devscripts fakeroot g++ git lsb-release tar wget
          apt-get install -y --no-install-recommends catch cmake g++ libgl-dev libglfw3-dev libwebp-dev pkg-config
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - name: Git checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Prepare Git repository
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --force --tags
      - name: Build package
        run: |
          export CXX=g++
          export CC=gcc
          cd "$GITHUB_WORKSPACE"
          ./ci/02-create-package.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.pack-name }}
          path: webp*.deb
