name: Debian packages

on:
  push:
    tags:
      - v*

jobs:
  package:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04, ubuntu-24.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Force-fetch Git tags
        run: git fetch --force --tags
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends build-essential bzip2 ca-certificates debhelper devscripts fakeroot g++ git lsb-release tar wget
          sudo apt-get install -y --no-install-recommends cmake g++ libgl-dev libglfw3-dev libwebp-dev pkg-config
      - name: Install Catch v1
        run: |
          sudo apt-get install -y --no-install-recommends catch
        if: matrix.os != 'ubuntu-24.04'
      - name: Install Catch v2 / v3
        run: |
          sudo apt-get install -y --no-install-recommends catch2
        if: matrix.os == 'ubuntu-24.04'
      - name: Build package
        run: |
          export CXX=g++
          export CC=gcc
          cd "$GITHUB_WORKSPACE"
          ./ci/02-create-package.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.os }}
          path: webp*.deb
